### ISSUE TITLE
termbox-bindings-0.1.0.0 does not compile

### ISSUE THREAD

**Issue by peti** [luciferous/termbox-bindings#1]
Citing from http://hydra.cryp.to/build/805080/log/raw:

```
Setup: TB_INCLUDE_DIR: getEnv: does not exist (no environment variable)
```

Why do you hard-code that variable name instead of allowing the user to specify the standard `--extra-include-dirs=PATH` flag?

**Comment by luciferous** [comment]
cabal doesn't pick this up for some reason, so this environment var is a
workaround.

**Comment by luciferous** [comment]
Is there a better way to do this? Should I be bundling the c lib that I'm
wrapping and getting cabal to compile everything together?

**Comment by peti** [comment]
What do you mean by "cabal doesn't pick this up"?

**Comment by luciferous** [comment]
It causes cabal build to abort the operation, thinking its an invalid flag.

**Comment by peti** [comment]
> It causes cabal build to abort the operation, thinking its an invalid flag.

What exactly does the command-line look like that you call to configure the build? Can you paste the complete command, please?

**Comment by luciferous** [comment]
Sure!

```
$ cabal build --extra-lib-dirs=.termbox/dist/lib
cabal: unrecognized 'build' option `--extra-lib-dirs=.termbox/dist/lib'

$ cabal build --extra-include-dirs=.termbox/src
cabal: unrecognized 'build' option `--extra-include-dirs=.termbox/src'
```

**Comment by peti** [comment]
You have to pass these options during `cabal configure`, not `cabal build`:

```
$ cabal configure  --extra-lib-dirs=.termbox/dist/lib --extra-include-dirs=.termbox/src
$ cabal build
```

**Comment by luciferous** [comment]
But then cabal build complains about relative path of library directories.

```
$ cabal build
Building termbox-bindings-0.1.0.0...
Preprocessing library termbox-bindings-0.1.0.0...
[...snip...]
/Users/nvong/.src/termbox-bindings/dist/doc/html/termbox-bindings doesn't
exist or isn't a directory
termbox-bindings-0.1.0.0: library-dirs: .termbox/dist/lib is a relative path
which makes no sense (as there is nothing for it to be relative to). You can
make paths relative to the package database itself by using ${pkgroot}. (use
--force to override)
```

**Comment by luciferous** [comment]
Maybe this means I should require the user to pass in an absolute path?

**Comment by luciferous** [comment]
Ok, I changed Setup.hs and updated the docs to use a separate configure and build (b95c12d).

**Comment by peti** [comment]
OK. Thank you very much for your efforts!
